run:
  timeout: 1m
  issues-exit-code: 2
  tests: false
  go: '1.21'

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gofumpt
    - gci
    - wrapcheck
    - varnamelen
    - gochecknoglobals
    - nonamedreturns
    - exhaustruct
    - exhaustivestruct
    - nlreturn
    - nosnakecase
    - depguard
    - tagalign

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        mapstructure: snake
  cyclop:
    max-complexity: 8