openapi: 3.0.3
info:
  title: WVMC
  version: 2.0.0
servers:
  - url: http://localhost:8101
    description: localhost
  - url: https://dc.kmsys.ru:53338
    description: Основной сервер
paths:
  /signin:
    post:
      tags:
        - Регистрация и аутентификация
      summary: Вход
      description: Вход по логину паролю
      requestBody:
        $ref: '#/components/requestBodies/SignIn'
      responses:
        200:
          $ref: '#/components/responses/SignIn'
  /refresh:
    post:
      tags:
        - Регистрация и аутентификация
      summary: Обновление пары токенов
      description: Обновление пары токенов
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                refresh_token: <token>
      responses:
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'
  /users:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Пользователи
      summary: Просмотр пользователей
      description: Просмотр пользователей приложения
      responses:
        200:
          $ref: '#/components/responses/GetUsers'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          description: Уникальный идентификатор
          type: string
          example: "5"
        name:
          description: Имя
          type: string
          example: anaxita
        email:
          description: Логин
          type: string
          example: support@mail.ru
        company:
          description: Компания
          type: string
          example: КМ Системс
        role:
          description: Уровень прав
          type: integer
          example: 0
    Server:
      title: Server
      type: object
      properties:
        id:
          description: Уникальный идентификатор
          type: string
          example: "sdfg-324df-bnn-df-df"
        name:
          description: Имя
          type: string
          example: SRV_SERVER_ONE
        ip4:
          description: IP4 адрес
          type: string
          example: "172.168.12.33"
        hv:
          description: Гипервизор
          type: string
          example: HV07
        user:
          description: Учетная запись
          type: string
          example: Administrator
        password:
          description: Пароль учетной записи
          type: string
          example: qwerty123
        power_status:
          description: Статус работы
          type: integer
          example: 2
        network:
          description: Статус сети
          type: integer
          example: 2
    SignInRequest:
      required: [ email, password ]
      title: SignInRequest
      type: object
      properties:
        email:
          description: Логин
          type: string
          example: admin
        password:
          description: Пароль
          type: string
          example: dev
    SignInResponse:
      required: [ access_token, refresh_token ]
      title: SignInResponse
      type: object
      properties:
        access_token:
          description: Access token
          type: string
          example: 123
        refresh_token:
          description: Refresh token
          type: string
          example: 123
  requestBodies:
    SignIn:
      required: true
      description: Тело запроса для авторизации
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SignInRequest'
  responses:
    SignIn:
      description: Тело ответа для авторизации
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SignInResponse'
    GetUsers:
      description: Тело ответа для получения пользователей
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'